[client]
showSidebarNavigation = false

[theme]

# Primary accent for interactive elements
primaryColor = '#7792E3'

# Background color for the main content area
backgroundColor = '#FFE9D5' 

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#F1E7FB'

# Color used for almost all text
textColor = '#000000'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"